# Tensorflow2.0 小练习

In [1]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [23]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，=>axis=-1
    不允许用tf自带的softmax函数'''
    ##########
    #tf.nn.softmax是直接调用
    exp_x=np.exp(x)
    #print(exp_x)
    prob_x=exp_x/np.sum(exp_x,axis=-1, keepdims=True) #二维数组中axis=-1代表沿着行方向求和，keepdims=True代表保持原始数组维度
    #print(prob_x)
    return prob_x

test_data = np.random.normal(size=[10, 5])
print("test_data:\n",test_data)
#print(softmax(test_data))#2026.3.15
#print(tf.nn.softmax(test_data, axis=-1).numpy())#2026.3.15
(softmax(test_data)- tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

test_data:
 [[ 1.22380563  0.81818242 -1.32802871 -2.28272397  0.15985756]
 [ 1.60618304 -0.65098444  1.16821544  0.28101304  0.48016552]
 [ 0.54729334  1.64580288 -0.25494738 -0.43437172  0.43175307]
 [-0.97974349  0.91016065  0.01723287 -0.9786251  -0.08094929]
 [-1.34976007  0.50980645  0.05068315 -0.08938406  0.18853805]
 [-0.24260567 -1.61828095 -0.88607375  0.62010785  1.42855899]
 [ 1.88688525 -0.02216711  0.11357735 -0.28883439  0.49369159]
 [ 1.75000452  0.03553611 -0.50431674  0.40082046  0.96281973]
 [ 1.50390875 -1.80968688  0.13190824  0.16504173  0.4892691 ]
 [-1.23083263  0.20514985 -0.53154594  0.27755731 -1.38229616]]


array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [25]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    prob_x=1/(1+np.exp(-x))
    return prob_x

test_data = np.random.normal(size=[10, 5])
#print(test_data)
#print(sigmoid(test_data))#2026.3.15
#print(tf.nn.sigmoid(test_data).numpy())#2026.3.15
(sigmoid(test_data) - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [55]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    #print(label)
    #print(x)
    #print(np.log(x))
    loss=np.sum(-label*np.log(x),axis=-1,keepdims=False)
    print(loss,loss.shape,loss.dtype)
    return np.mean(loss)

test_data = np.random.normal(size=[10, 5])#test_data 10个样本，每个样本有5个特征值。
prob = tf.nn.softmax(test_data)#softmax处理过
label = np.zeros_like(test_data)#初始化全零数组
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.#随机标定一个样本标签--10个样本，每个样本属于5个类别之一，并且采用了one-hot编码。
#print(label,label.shape,prob.shape)
#loss=softmax_ce(prob,label)
print(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))- softmax_ce(prob, label))**2 < 0.0001).numpy()


tf.Tensor(
[0.67818443 2.4441694  1.52836565 0.96381463 2.20521818 2.77209208
 0.64813211 2.40055348 0.81462492 1.09758078], shape=(10,), dtype=float64)
[0.67818443 2.4441694  1.52836565 0.96381463 2.20521818 2.77209208
 0.64813211 2.40055348 0.81462492 1.09758078] (10,) float64


np.True_

## 实现 sigmoid 交叉熵loss函数

In [67]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    loss=-(label*np.log(x)+(1-label)*np.log(1-x))
    print("my sigmoid:\n",loss,loss.shape,loss.dtype)
    return np.mean(loss)

test_data = np.random.normal(size=[10])
#print(test_data)
prob = tf.nn.sigmoid(test_data)
#print(prob)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print ("label:\n",label)
print("tf sigmoid:\n",tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))
((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


label:
 [1. 1. 0. 1. 1. 0. 0. 1. 1. 1.]
tf sigmoid:
 tf.Tensor(
[1.09094296 0.99621259 0.63087297 0.31709678 2.11741873 0.6310859
 0.42572052 0.59473158 0.55225669 0.63098828], shape=(10,), dtype=float64)
my sigmoid:
 [1.09094296 0.99621259 0.63087297 0.31709678 2.11741873 0.6310859
 0.42572052 0.59473158 0.55225669 0.63098828] (10,) float64


np.True_